import { jsPDF } from 'jspdf';
import { applyPlugin } from 'jspdf-autotable';
applyPlugin(jsPDF);
import { ALS_GROUPS } from './constants';
import { toBillingQty, getDisplayUnit } from '../utils/units';
import { formatDate } from '../utils/dateHelpers';

export function billingUnitLabel(dbUnit, nosPerKg) {
  if (nosPerKg && nosPerKg > 0) return 'Kg';
  return getDisplayUnit(dbUnit);
}

// ─── Currency formatter ──────────────────────────────────────────────────────
const fmtCurrency = (v) =>
  v === 0 ? '—' : '₹' + v.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const fmtQty = (v) =>
  v === 0 ? '—' : v.toFixed(3).replace(/\.?0+$/, '');

// ─── Colours ─────────────────────────────────────────────────────────────────
const GREEN      = [0, 130, 120];   // Metro teal-green
const GREEN_DARK = [0, 100, 92];
const WHITE      = [255, 255, 255];
const GRAY_ROW   = [248, 250, 249]; // subtle alternating row

// ─── Logo helper (canvas → JPEG, white background) ───────────────────────────
async function loadLogoAsJpeg() {
  const response = await fetch('/kmrl_logo.png');
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      resolve(canvas.toDataURL('image/jpeg', 1.0));
    };
    img.onerror = reject;
    img.src = url;
  });
}

// ─── Draw the professional page header (logo + title + info row) ─────────────
async function drawPageHeader(doc, month, year, logoJpeg, monthName) {
  const W = doc.internal.pageSize.getWidth();
  const margin = 14;

  // ── Logo ──
  if (logoJpeg) {
    try { doc.addImage(logoJpeg, 'JPEG', margin, 6, 28, 14); } catch (_) {}
  }

  // ── Organisation name (centre) ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('KOCHI METRO RAIL LIMITED', W / 2, 12, { align: 'center' });

  // ── Document ref (top-right) ──
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.text('KMRL-O&M-OPC-FOR-150', W - margin, 8,  { align: 'right' });
  doc.text('Revision No: 01',       W - margin, 13, { align: 'right' });
  doc.text(`Date: ${formatDate(new Date())}`, W - margin, 18, { align: 'right' });

  // ── Separator line ──
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.5);
  doc.line(margin, 21, W - margin, 21);

  // ── Title bar ──
  doc.setFillColor(...GREEN);
  doc.roundedRect(margin, 23, W - margin * 2, 9, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...WHITE);
  doc.text('Cleaning Material Consumption (Stations)', W / 2, 29, { align: 'center' });

  // ── Info row ──
  doc.setFillColor(235, 248, 246);
  doc.rect(margin, 32, W - margin * 2, 7, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(30, 30, 30);
  const infoY = 36.5;
  doc.setFont('helvetica', 'bold');
  doc.text(`Month: `, margin + 3, infoY);
  doc.setFont('helvetica', 'normal');
  doc.text(`${monthName} ${year}`, margin + 3 + doc.getTextWidth('Month: '), infoY);
  doc.setFont('helvetica', 'bold');
  doc.text(`Station Type: `, W / 2 - 20, infoY);
  doc.setFont('helvetica', 'normal');
  doc.text('All Stations (Aggregated)', W / 2 - 20 + doc.getTextWidth('Station Type: '), infoY);
  doc.setFont('helvetica', 'bold');
  doc.text(`Generated On: `, W - margin - 60, infoY);
  doc.setFont('helvetica', 'normal');
  doc.text(formatDate(new Date()), W - margin - 60 + doc.getTextWidth('Generated On: '), infoY);

  doc.setTextColor(0, 0, 0);
  return 40; // Y where table should start
}

// ─── Draw the footer on each page ────────────────────────────────────────────
function drawPageFooter(doc, logoJpeg, pageNum, totalPages) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 14;
  const footY = H - 10;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, footY - 5, W - margin, footY - 5);

  // Logo (small)
  if (logoJpeg) {
    try { doc.addImage(logoJpeg, 'JPEG', margin, footY - 4, 12, 6); } catch (_) {}
  }

  // Centre text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text('Metro HK Portal — Housekeeping & Inventory Management System', W / 2, footY - 1, { align: 'center' });
  doc.text('Generated by Metro HK Portal', W / 2, footY + 3, { align: 'center' });

  // Page number (right)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(60, 60, 60);
  doc.text(`Page ${pageNum} of ${totalPages}`, W - margin, footY, { align: 'right' });
  doc.setTextColor(0, 0, 0);
}

// ─── Main export ─────────────────────────────────────────────────────────────
export const generateMonthlyBillPdf = async (month, year, consumptionData, allItems = []) => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const monthName = new Date(year, month - 1)
    .toLocaleString('default', { month: 'long' })
    .toUpperCase();

  // Load logo once
  let logoJpeg = null;
  try { logoJpeg = await loadLogoAsJpeg(); } catch (_) { console.warn('Logo load failed'); }

  // ─── Build item map (no changes to calculation logic) ───────────────────────
  const groupedItems = {};

  allItems.forEach(item => {
    const tYearStr = item.rate_master?.tender_year || '';
    if (tYearStr.toLowerCase().includes('before 2024')) return;
    const startYear = parseInt(tYearStr.split('-')[0]) || 0;
    if (startYear > 0 && startYear < 2024) return;

    const dbUnit   = item.unit || 'Nos';
    const nosPerKg = item.rate_master?.nos_per_kg || null;
    groupedItems[item.id] = {
      name:      item.name,
      brand:     item.rate_master?.brand    || 'ORDINARY',
      supplier:  item.rate_master?.supplier || 'Tricuesta',
      rate:      Number(item.rate_master?.unit_rate || 0),
      dbUnit,
      nosPerKg,
      'ALVA-KLMT': 0,
      'CCUV-JLSD': 0,
      'KALR-KVTR': 0,
      'EMKM-TPHT': 0,
    };
  });

  consumptionData.forEach(log => {
    const itemId      = log.item_id;
    const stationCode = log.stations?.code;
    const qty         = Number(log.quantity_used || 0);

    if (!groupedItems[itemId]) {
      const tYearStr = log.inventory_items?.rate_master?.tender_year || '';
      if (tYearStr.toLowerCase().includes('before 2024')) return;
      const startYear = parseInt(tYearStr.split('-')[0]) || 0;
      if (startYear > 0 && startYear < 2024) return;

      const dbUnit   = log.inventory_items?.unit || 'Nos';
      const nosPerKg = log.inventory_items?.rate_master?.nos_per_kg || null;
      groupedItems[itemId] = {
        name:     log.inventory_items?.name || 'Unknown',
        brand:    log.inventory_items?.rate_master?.brand    || 'ORDINARY',
        supplier: log.inventory_items?.rate_master?.supplier || 'Tricuesta',
        rate:     Number(log.inventory_items?.rate_master?.unit_rate || 0),
        dbUnit,
        nosPerKg,
        'ALVA-KLMT': 0,
        'CCUV-JLSD': 0,
        'KALR-KVTR': 0,
        'EMKM-TPHT': 0,
      };
    }

    if      (ALS_GROUPS['ALVA-KLMT'].includes(stationCode)) groupedItems[itemId]['ALVA-KLMT'] += qty;
    else if (ALS_GROUPS['CCUV-JLSD'].includes(stationCode)) groupedItems[itemId]['CCUV-JLSD'] += qty;
    else if (ALS_GROUPS['KALR-KVTR'].includes(stationCode)) groupedItems[itemId]['KALR-KVTR'] += qty;
    else if (ALS_GROUPS['EMKM-TPHT'].includes(stationCode)) groupedItems[itemId]['EMKM-TPHT'] += qty;
  });

  // ─── Build table rows (same calculation, improved display) ──────────────────
  let totalALVA = 0, totalCCUV = 0, totalKALR = 0, totalEMKM = 0, grandTotal = 0;

  const tableData = Object.values(groupedItems).map((item, index) => {
    const { dbUnit, nosPerKg, rate } = item;
    const alvaQty = toBillingQty(item['ALVA-KLMT'], dbUnit, nosPerKg);
    const ccuvQty = toBillingQty(item['CCUV-JLSD'], dbUnit, nosPerKg);
    const kalrQty = toBillingQty(item['KALR-KVTR'], dbUnit, nosPerKg);
    const emkmQty = toBillingQty(item['EMKM-TPHT'], dbUnit, nosPerKg);
    const totalQty = alvaQty + ccuvQty + kalrQty + emkmQty;
    const amount   = totalQty * rate;

    totalALVA += alvaQty * rate;
    totalCCUV += ccuvQty * rate;
    totalKALR += kalrQty * rate;
    totalEMKM += emkmQty * rate;
    grandTotal += amount;

    return [
      index + 1,
      item.name,
      item.brand,
      item.supplier,
      rate > 0 ? rate.toLocaleString('en-IN', { minimumFractionDigits: 2 }) : '—',
      fmtQty(alvaQty),
      fmtQty(ccuvQty),
      fmtQty(kalrQty),
      fmtQty(emkmQty),
      fmtQty(totalQty),
      amount > 0
        ? amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
        : '—',
    ];
  });

  // ─── Foot totals row ─────────────────────────────────────────────────────────
  const footData = [[
    { content: 'TOTAL', colSpan: 5, styles: { halign: 'center', fontStyle: 'bold', fontSize: 9 } },
    { content: totalALVA > 0 ? totalALVA.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '—', styles: { halign: 'right', fontStyle: 'bold' } },
    { content: totalCCUV > 0 ? totalCCUV.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '—', styles: { halign: 'right', fontStyle: 'bold' } },
    { content: totalKALR > 0 ? totalKALR.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '—', styles: { halign: 'right', fontStyle: 'bold' } },
    { content: totalEMKM > 0 ? totalEMKM.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '—', styles: { halign: 'right', fontStyle: 'bold' } },
    { content: '—', styles: { halign: 'center' } },
    { content: grandTotal.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }), styles: { halign: 'right', fontStyle: 'bold', fontSize: 9 } },
  ]];

  // ─── Draw first page header ───────────────────────────────────────────────
  const startY = await drawPageHeader(doc, month, year, logoJpeg, monthName);

  // ─── autoTable ───────────────────────────────────────────────────────────
  let pageCount = 0;
  doc.autoTable({
    startY,
    head: [[
      'Sl.\nNo',
      'Cleaning Material',
      'Brand',
      'Supplier',
      'Rate (₹)',
      'ALVA-KLMT',
      'CCUV-JLSD',
      'KALR-KVTR',
      'EMKM-TPHT',
      'Total',
      'Amount (₹)',
    ]],
    body: tableData,
    foot: footData,
    showFoot: 'lastPage',
    theme: 'grid',
    headStyles: {
      fillColor: GREEN,
      textColor: WHITE,
      fontStyle: 'bold',
      halign: 'center',
      valign: 'middle',
      fontSize: 8,
      cellPadding: { top: 3, bottom: 3, left: 2, right: 2 },
    },
    footStyles: {
      fillColor: GREEN_DARK,
      textColor: WHITE,
      fontStyle: 'bold',
      fontSize: 9,
      cellPadding: { top: 4, bottom: 4, left: 2, right: 2 },
    },
    styles: {
      fontSize: 7.5,
      cellPadding: { top: 2.5, bottom: 2.5, left: 2.5, right: 2.5 },
      valign: 'middle',
      lineColor: [220, 220, 220],
      lineWidth: 0.2,
      overflow: 'linebreak',
    },
    alternateRowStyles: {
      fillColor: GRAY_ROW,
    },
    columnStyles: {
      0:  { halign: 'center', cellWidth: 9,  fontStyle: 'bold' },
      1:  { cellWidth: 48 },                          // Cleaning Material — widest
      2:  { cellWidth: 22 },                          // Brand
      3:  { cellWidth: 24 },                          // Supplier
      4:  { halign: 'right',  cellWidth: 18 },        // Rate
      5:  { halign: 'center', cellWidth: 18 },        // ALVA-KLMT
      6:  { halign: 'center', cellWidth: 18 },        // CCUV-JLSD
      7:  { halign: 'center', cellWidth: 18 },        // KALR-KVTR
      8:  { halign: 'center', cellWidth: 18 },        // EMKM-TPHT
      9:  { halign: 'center', cellWidth: 14 },        // Total
      10: { halign: 'right',  cellWidth: 22, fontStyle: 'bold' }, // Amount
    },
    // Repeat header on every page + re-draw our custom header
    didDrawPage: (hookData) => {
      pageCount = hookData.pageNumber;
      // On pages after the first, redraw the top header
      if (hookData.pageNumber > 1) {
        // Async logo already loaded — use synchronous version inside hook
        if (logoJpeg) {
          try { doc.addImage(logoJpeg, 'JPEG', 14, 6, 28, 14); } catch (_) {}
        }
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        const W = doc.internal.pageSize.getWidth();
        doc.text('KOCHI METRO RAIL LIMITED', W / 2, 12, { align: 'center' });

        doc.setDrawColor(...GREEN);
        doc.setLineWidth(0.5);
        doc.line(14, 21, W - 14, 21);

        doc.setFillColor(...GREEN);
        doc.roundedRect(14, 23, W - 28, 9, 1, 1, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(...WHITE);
        doc.text('Cleaning Material Consumption (Stations)', W / 2, 29, { align: 'center' });
        doc.setTextColor(0, 0, 0);
      }
    },
    margin: { top: 42, left: 14, right: 14, bottom: 16 },
    pageBreak: 'auto',
    rowPageBreak: 'avoid',
  });

  // ─── Add footer to every page ────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageFooter(doc, logoJpeg, p, totalPages);
  }

  doc.save(`KMRL_Consumption_Bill_${monthName}_${year}.pdf`);
};
